# Generated by Django 5.0 on 2024-01-21 17:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre Producto')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('descripcion', models.TextField(blank=True, default='', max_length=250, null=True)),
                ('imagen', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre Usuario')),
                ('Apellido', models.CharField(max_length=120, verbose_name='Apellido Usuario')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=120, verbose_name='contraseña')),
                ('celular', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('direccion', models.CharField(blank=True, default='', max_length=150)),
                ('celular', models.CharField(blank=True, default='', max_length=50)),
                ('fecha', models.DateField(default=datetime.datetime.today)),
                ('estado', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
    ]
