# Generated by Django 5.0 on 2024-01-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_producto_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Esta_en_Descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='Precio_Anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
