# Generated by Django 5.0 on 2024-01-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_producto_esta_en_descuento_producto_precio_anterior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Precio_Anterior',
            new_name='Precio_Descuento',
        ),
    ]
